chore: notifications indicator on the learn tab
edx/edx-mobile-marketplace-ios pull request #107
Opened 2024-12-20 13:54 UTC by saeedbashir

### Description

Show the notifications icon on the learn tab to access the notification inbox.

Note: The redirection to inbox will be handled under a separate ticket.

Figma: https://www.figma.com/design/I9xgrJzdTje5vKgh6DD57C/Mobile-UI-Screens-(2025)?node-id=4-1973&t=QVMsGjgiGUtw15ry-0

| Light Mode  | Dark Mode |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 16 Pro - 2024-12-20 at 16 35 13](https://github.com/user-attachments/assets/8ae3e606-cae1-483e-a18f-6a5d33748c97) | ![Simulator Screenshot - iPhone 16 Pro - 2024-12-20 at 18 51 10](https://github.com/user-attachments/assets/7daf9a9d-bb4e-47af-ae68-712464b9a23d) |

2024-12-24 08:35 UTC, shafqat-muneer commented
@saeedbashir Noticed two minor UI enhancements:

1. An outer red rounded border is visible, which ideally shouldn't be present. This issue appears in both light and dark modes.
2. As per the Figma design, the red indicator's RGB shades differ between dark and light modes.

Kindly address them.

**Figma Design:**
<img width="212" alt="Screenshot 2024-12-24 at 1 32 59 PM" src="https://github.com/user-attachments/assets/59348a5a-5e8f-484c-a878-c564c5a21f69" />

**Implemented Design Preview:**
<img width="825" alt="Screenshot 2024-12-24 at 1 34 39 PM" src="https://github.com/user-attachments/assets/422cb8d6-394a-4ded-8917-77ebddbab916" />

2024-12-24 12:05 UTC, shafqat-muneer requested changes

2024-12-24 12:05 UTC, shafqat-muneer commented on Notifications/Notifications/Data/Model/NotificationsCountByApp.swift
> +
Vertical Whitespace Violation: Limit vertical whitespace to a single empty line; currently 2 (vertical_whitespace)

2024-12-24 12:05 UTC, shafqat-muneer commented on Notifications/Notifications/Data/Model/NotificationsCountByApp.swift
> +public struct NotificationsCountByApp {
I feel `NotificationsCountByApp` might not be the best name. Perhaps we could consider `NotificationsCount` instead?

2024-12-24 12:05 UTC, shafqat-muneer commented on Notifications/Notifications/Data/Model/Data_NotificationsCountByApp.swift
Should we consider using the file name without an underscore?

2024-12-24 12:05 UTC, shafqat-muneer commented on Notifications/Notifications/Data/Model/Data_NotificationsCountByApp.swift
> +            case grading
Since we’re not using these two types at the moment, should we still add them now?

2024-12-26 06:06 UTC, saeedbashir commented
> As per the Figma design, the red indicator's RGB shades differ between dark and light modes.

In the whole app we are using same color note for brand accent color so thats why didn't change it here as well.

2024-12-26 06:07 UTC, saeedbashir commented on Notifications/Notifications/Data/Model/Data_NotificationsCountByApp.swift
This is the convention being used in the codebase.

2024-12-26 10:19 UTC, shafqat-muneer approved these changes
LGTM 👍

2024-12-26 11:32 UTC, merged

2024-12-26 12:06 UTC, rnr commented on Dashboard/Dashboard/Presentation/PrimaryCourseDashboardView.swift
> +                        Button(action: {
@saeedbashir Maybe we should check `pushNotificationsEnabled` setting to show this button?