chore: analytics improvements for reporting
edx/edx-mobile-marketplace-ios pull request #16
Opened 2024-07-08 10:24 UTC by saeedbashir

This PR improves analytics for IAP events by sending LMS returned price, localized price, and localized currency code for better reporting as requested by the product.

2024-07-08 12:19 UTC, rnr approved these changes

2024-07-09 19:14 UTC, shafqat-muneer requested changes

2024-07-09 19:14 UTC, shafqat-muneer commented on Core/Core/CourseUpgrade/CourseUpgradeHelper.swift
> +            saveInProgressIAP(courseID: courseID, sku: sku, lmsPrice: lmsPrice ?? 0.0)
At few places, we are using default value as .zero. For consistency, please use same on all places.

2024-07-09 19:14 UTC, shafqat-muneer commented on Core/Core/CourseUpgrade/ViewModels/UpgradeInfoViewModel.swift
> +                        lmsPrice: lmsPrice,
These values accessible at this point. Shouldn't we use these values?
```
localizedPrice: product?.price,
localizedCurrencyCode: product?.currencySymbol,
```

2024-07-09 19:14 UTC, shafqat-muneer commented on Core/Core/CourseUpgrade/ViewModels/UpgradeInfoViewModel.swift
> +                    localizedPrice: nil,
This values accessible at this point. Shouldn't we use these values?
```
localizedPrice: product?.price
```

2024-07-09 19:14 UTC, shafqat-muneer commented on OpenEdX/Data/DashboardPersistence.swift
> +                                  lmsPrice: $0.lmsPrice)}
Please move closing brace of `.map` closure to next line.

2024-07-10 02:24 UTC, saeedbashir commented on Core/Core/CourseUpgrade/ViewModels/UpgradeInfoViewModel.swift
> +                        lmsPrice: lmsPrice,
It's a price fetching error so in any case these will be nil.

2024-07-10 02:25 UTC, saeedbashir commented on Core/Core/CourseUpgrade/ViewModels/UpgradeInfoViewModel.swift
> +                    localizedPrice: nil,
https://github.com/edx/edx-mobile-marketplace-ios/pull/16#discussion_r1671481443

2024-07-10 10:48 UTC, shafqat-muneer requested changes

2024-07-10 10:48 UTC, shafqat-muneer commented on Core/Core/CourseUpgrade/CourseUpgradeHelper.swift
> +        lmsPrice = coder.decodeObject(forKey: "lmsPrice") as? Double ?? 0.0
Please also update here `lmsPrice ?? 0.0` to `lmsPrice ?? .zero`

2024-07-11 12:53 UTC, shafqat-muneer approved these changes
LGTM 👍

2024-07-11 12:53 UTC, merged