chore: remove unnecessary FC-47 items from the MVP
edx/edx-mobile-marketplace-ios pull request #20
Opened 2024-07-15 05:40 UTC by saeedbashir

The following items need to be removed as they are not necessary for our MVP launch and seem half-baked items from FC47 changes. 

1. Lock icon on course cards - we are not sure about the current logic and all the cases involved for showing the lock icon on course cards hence we have decided to remove this feature from the MVP and look into it closely post-mvp and give it more thought. 
2. Notification-related API implementation `/api/mobile/v4/notifications/create-token/`
3. Calendar sync settings - We also need to remove the Calendar Sync settings added in the settings screen under video download settings. Our calendar sync functionality does not work like this.

2024-07-15 11:34 UTC, shafqat-muneer requested changes

2024-07-15 11:34 UTC, shafqat-muneer commented on Dashboard/Dashboard/Presentation/Elements/CourseCardView.swift
> +//            }
Let's comment it like this. Multiline comment seems more appropriate here.
```
/*
// Commenting this for MVP, LEARNER-10102
if !hasAccess {
    ZStack(alignment: .center) {
        Circle()
            .foregroundStyle(Theme.Colors.primaryHeaderColor)
            .opacity(0.7)
            .frame(width: 24, height: 24)
        CoreAssets.lockIcon.swiftUIImage
            .foregroundStyle(Theme.Colors.textPrimary)
    }
    .padding(8)
}
 */
```

2024-07-15 11:44 UTC, rnr approved these changes

2024-07-16 05:56 UTC, shafqat-muneer approved these changes
LGTM 👍

2024-07-16 06:18 UTC, merged