fix: fix iPad crash of alert controller
edx/edx-mobile-marketplace-ios pull request #74
Opened 2024-08-29 02:23 UTC by saeedbashir

This PR fixes the following iPad Crash. Although I couldn't reproduce the crash in the actual case, the crash happened when I ran the same code by clicking a button.

<img width="1117" alt="crash_logs" src="https://github.com/user-attachments/assets/09e5a7e5-3e4b-4f77-8de5-2954b59f1a7c">

2024-08-30 11:04 UTC, rnr approved these changes

2024-09-03 11:27 UTC, shafqat-muneer requested changes
`UIAlertController` is also using in `UIAlertController+BlockActions.swift`. If it's applicable then we should also add it there.

2024-09-03 12:43 UTC, shafqat-muneer commented
> `UIAlertController` is also using in `UIAlertController+BlockActions.swift`. If it's applicable then we should also add it there.

After discussion with @saeedbashir, it will not create issue at this point because style type is `UIAlertController.Style.alert` at this specific location. The places where style type is `.actionSheet`, we need to address it.

Approving the PR. Change is LGTM

2024-09-03 12:43 UTC, shafqat-muneer approved these changes

2024-09-04 02:26 UTC, merged