chore: Elm theme improvements for modals and alerts
edx/edx-mobile-marketplace-ios pull request #91
Opened 2024-10-22 09:20 UTC by saeedbashir

### Description

Jira Ticket: [LEARNER-10148](https://2u-internal.atlassian.net/browse/LEARNER-10148)

| Before  | After |
| ------------- | ------------- |
| ![7](https://github.com/user-attachments/assets/d77b79d5-bdc0-421e-b135-83cd3b410031) |![Simulator Screenshot - iPhone 16 Pro - 2024-10-22 at 13 38 30](https://github.com/user-attachments/assets/689a214e-489d-42dc-b20a-1df463d31c56)|
| ![6](https://github.com/user-attachments/assets/b39e2a17-962a-46a8-ba91-065572c84beb) | ![2](https://github.com/user-attachments/assets/bd2cee10-2ccf-4d3e-af75-433bd6e2962d)  |
| ![4](https://github.com/user-attachments/assets/9ae6981a-6427-4887-b2d6-f9f08f400d68) |  ![3](https://github.com/user-attachments/assets/97fe7e59-ea38-480a-91db-889950c79092) |

2024-10-22 13:52 UTC, rnr approved these changes

2024-10-25 07:57 UTC, shafqat-muneer requested changes

2024-10-25 07:57 UTC, shafqat-muneer commented on Discovery/Discovery/Presentation/WebDiscovery/DiscoveryWebviewViewModel.swift
> +                            action: "continue"
Can we use `CoreLocalization.Webview.Alert.continue` here?

2024-10-25 07:57 UTC, shafqat-muneer commented on Discovery/Discovery/Presentation/WebDiscovery/DiscoveryWebviewViewModel.swift
> +                            action: "cancel"
Can we use `CoreLocalization.Webview.Alert.cancel`?

2024-10-25 09:14 UTC, saeedbashir commented on Discovery/Discovery/Presentation/WebDiscovery/DiscoveryWebviewViewModel.swift
> +                            action: "continue"
It's for the analytics, if we use the localized string then it will be different as per the language and it will be hard to group the event based on value.

2024-10-25 09:14 UTC, saeedbashir commented on Discovery/Discovery/Presentation/WebDiscovery/DiscoveryWebviewViewModel.swift
> +                            action: "cancel"
https://github.com/edx/edx-mobile-marketplace-ios/pull/91#discussion_r1816319167

2024-10-25 11:02 UTC, shafqat-muneer approved these changes

2024-10-28 05:15 UTC, merged