chore: sign-in and register screens social sign in improvements
edx/edx-mobile-marketplace-ios pull request #95
Opened 2024-11-18 12:01 UTC by saeedbashir

### Description 

#### Jira Tickets:
[LEARNER-10296](https://2u-internal.atlassian.net/browse/LEARNER-10296)
[LEARNER-10297](https://2u-internal.atlassian.net/browse/LEARNER-10297)

#### Config:
https://github.com/edx/edx-mobile-config/pull/186

#### Screenshots

| Axim Light  | Axim Dark | edX Light  | edx Dark |
| ------------- | ------------- | ------------- | ------------- |
| ![axim_sign_in_light](https://github.com/user-attachments/assets/79365f10-47e0-4abe-9043-33e3198ba9af) | ![axim_sign_in](https://github.com/user-attachments/assets/8ee51f0b-2260-431c-bb45-2ce24c3497a8) | ![edx_sign_in-light](https://github.com/user-attachments/assets/56aa1d2e-1d37-4217-98a2-87d91b839999) | ![edx_sign_in](https://github.com/user-attachments/assets/bebcd04e-fcae-4454-bc9f-279ce2a20034) |
| ![axim_last_sign_in_light](https://github.com/user-attachments/assets/97f4594b-5a55-4ac7-aef4-57ee455c972b) | ![axim_last_sign_in](https://github.com/user-attachments/assets/56883db4-2b6b-48f2-9229-48b205ffcbdb) | ![edx_last_sign](https://github.com/user-attachments/assets/6e061310-2ebf-493c-b545-40051ef775cc) | ![edxa_last_sign_in](https://github.com/user-attachments/assets/195d680b-3e50-43da-9658-c3d6a011f238) |
| ![axim_register_light](https://github.com/user-attachments/assets/d2364602-b1a2-4f90-866a-b3092c663399) | ![axim_register](https://github.com/user-attachments/assets/67508c4d-d6c1-4ca9-8660-7d063c80b8fd) | ![edx_register_dark](https://github.com/user-attachments/assets/461fd492-43ea-45d0-9b2d-4ac916dcc8ba) | ![edx_register](https://github.com/user-attachments/assets/0d74e5f3-e128-4311-b716-6fa849cf2465) |

Note: I haven't implemented the more/less option for the social auth view. As at the moment, maximum 4 social auth options could be configured on mobile and more/less feature would be unused.
cc @moiz994

2024-11-18 13:00 UTC, rnr commented
Hello @saeedbashir 
Are these design changes approved by Axim? @marcotuts @sdaitzman 
Thank you

2024-11-18 13:49 UTC, rnr commented
Just Note: without corner radius 30 (edX specific) it looks like 
<img width="300" src="https://github.com/user-attachments/assets/b64f6dc7-b0e8-4620-a7fd-11491449d33b" >

2024-11-18 13:59 UTC, rnr commented
@saeedbashir @moiz994 Should Register screen says "Continue with"?

| Before | After |
| ------------- | ------------- |
| <img width="414" alt="Screenshot 2024-11-18 at 14 54 26" src="https://github.com/user-attachments/assets/ac2ffccc-be68-48cd-8c48-decaae407f76"> | <img width="405" alt="Screenshot 2024-11-18 at 14 54 50" src="https://github.com/user-attachments/assets/1ad18e83-a715-4715-97cd-dfe6abb56e83"> |

2024-11-18 14:06 UTC, saeedbashir commented
> Hello @saeedbashir Are these design changes approved by Axim? @marcotuts @sdaitzman Thank you

@rnr Yes, here is the [axim/schema figma file](https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Mobile-App-v2.3-%5BOpen-edX%5D?node-id=20477-160735&node-type=frame&t=x4BtOkBuMdZRnJDo-0) for the feature; we actually follow their design. And here is the [edX design file](https://www.figma.com/design/q6z6cpJsbBBcnPZLPS7KEu/Marketplace-Visual-Design?node-id=9077-11517).

2024-11-18 15:22 UTC, rnr commented
If we have only one auth service enabled then we don't need to show "separator" line: 
<img width="300" src="https://github.com/user-attachments/assets/df2e4ab5-f3b9-4293-9fa7-30a93475c6bb">

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
> +            UserDefaults.standard.set(auth.rawValue, forKey: "lastSocialAuthUsedOption")
@saeedbashir Where do we use this saved option `lastSocialAuthUsedOption`?

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/Login/SignInViewModel.swift
> +            var socialAuthMethod: String? = nil
`nil` value is redundant here

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
> +            UserDefaults.standard.set(auth.rawValue, forKey: "lastSocialAuthUsedOption")
Maybe we need to use `AppStorage` instead?

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
> +            var socialAuthMethod: String? = nil
`nil` value is redundant here

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
> +            UserDefaults.standard.set(auth.rawValue, forKey: "lastSocialAuthUsedOption")
Do we need this func at all if we save `lastUsedSocialAuth` in `showMainOrWhatsNewScreen`?

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/SocialAuth/SocialAuthView.swift
> +                    if option == viewModel.lastUsedOption, authType == .signIn {
Do we need this 'empty' `if` here? Why don't replace it with
```
if option != viewModel.lastUsedOption || authType != .signIn {
    socialAuthButton(option)
        .padding(.trailing, 16)
}
```

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/SocialAuth/SocialAuthView.swift
> +                socialAuthButton(lastOption)
Add new line before this view? Because all other views inside this `if` have this

2024-11-18 16:02 UTC, rnr commented on Authorization/Authorization/Presentation/SocialAuth/SocialAuthViewModel.swift
> +
Do we need this line in the start of function?

2024-11-19 04:43 UTC, saeedbashir commented on Authorization/Authorization/Presentation/Registration/SignUpViewModel.swift
> +            UserDefaults.standard.set(auth.rawValue, forKey: "lastSocialAuthUsedOption")
This method isn't needed.

2024-11-19 10:44 UTC, rnr approved these changes
LGTM! Thanks

2024-11-20 17:03 UTC, shafqat-muneer commented
After adding the last social sign-in option, the screen's left and right margins became misaligned and need to be fixed.

| Before Last Social Sign-in Option | After Last Social Sign-in Option |
|----------|----------|
| ![Simulator Screenshot - iPhone 16 - 2024-11-20 at 21 59 54](https://github.com/user-attachments/assets/30d28147-677c-4019-9169-b0f7e79f293a) | ![Simulator Screenshot - iPhone 16 - 2024-11-20 at 21 57 23](https://github.com/user-attachments/assets/470ce548-c2f0-41b3-8e32-f71ef9dc703e) |

2024-11-20 18:05 UTC, shafqat-muneer requested changes

2024-11-20 18:05 UTC, shafqat-muneer commented on Authorization/Authorization/Presentation/SocialAuth/SocialAuthView.swift
> +                _ in
Closure Parameter Position Violation: Closure parameters should be on the same line as opening brace (closure_parameter_position)

2024-11-20 18:05 UTC, shafqat-muneer commented on Core/Core/Assets.xcassets/Socials/icon_apple.imageset/icon_apple_white.png
**Suggestion:** Can we use .svg files here to prevent blurriness on high-resolution screens, even though no issues have been observed so far?

2024-11-22 07:28 UTC, saeedbashir commented on Core/Core/Assets.xcassets/Socials/icon_apple.imageset/icon_apple_white.png
We are using high-resolution images, so it's not needed.

2024-11-22 10:15 UTC, shafqat-muneer commented
LGTM 👍 

| After Last Social Sign-in Option |
|----------|
| <img src="https://github.com/user-attachments/assets/87580953-c3a1-404e-b3b3-889205647e55" width="200" height="434"> |

2024-11-22 10:17 UTC, shafqat-muneer approved these changes

2024-11-25 04:10 UTC, merged