fix: fix microsoft login issue on iOS after config branch merges
edx/edx-mobile-marketplace-ios pull request #96
Opened 2024-11-19 07:05 UTC by saeedbashir

### Description

Jira: [LEARNER-10308](https://2u-internal.atlassian.net/browse/LEARNER-10308)

Updated the terminology client ID instead of appID as client ID is also being used by the Microsoft SDK.

2024-11-19 11:03 UTC, rnr commented
@saeedbashir
Maybe the best place to change it is in the configuration repo? Since all teams in the open-source community would have to change their configurations after this key renaming. What do you think?
cc @touchapp @miankhalid

2024-11-22 05:20 UTC, saeedbashir commented
> Maybe the best place to change it is in the configuration repo? Since all teams in the open-source community would have to change their configurations after this key renaming. What do you think?

Android is/was using `CLIENT_KEY` and iOS was using `APP_ID`. It's better to update the config to use the same key for both platforms. And we decided to go with the Android one, as thats the convention the Microsoft SDK itself if using.

2024-11-22 11:13 UTC, rnr reviewed
code LGTM

2024-11-22 11:14 UTC, rnr commented
I think also needs to change this key in Documentation: https://github.com/edx/edx-mobile-marketplace-ios/blob/2U/develop/Documentation/CONFIGURATION_MANAGEMENT.md

2024-11-22 12:11 UTC, saeedbashir commented
> I think also needs to change this key in Documentation: https://github.com/edx/edx-mobile-marketplace-ios/blob/2U/develop/Documentation/CONFIGURATION_MANAGEMENT.md

Done

2024-11-22 12:21 UTC, rnr approved these changes

2024-11-25 08:00 UTC, shafqat-muneer requested changes

2024-11-25 08:00 UTC, shafqat-muneer commented on Core/Core/Providers/SocialAuth/MicrosoftAuthProvider.swift
> +        guard let config = Container.shared.resolve(ConfigProtocol.self), let clientID =  config.microsoft.clientID else {
Line Length Violation: Line should be 120 characters or less; currently it has 122 characters (line_length)

2024-11-25 11:18 UTC, shafqat-muneer approved these changes
LGTM 👍

2024-11-25 11:19 UTC, merged