chore: hide grades when sub section dependents not available
edx/edx-mobile-marketplace-ios pull request #99
Opened 2024-11-28 06:18 UTC by saeedbashir

### Description 

[LEARNER-10266](https://2u-internal.atlassian.net/browse/LEARNER-10266)

Hide the mid-term exam grading when descents aren't available. 

| Before  | After |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 16 Pro - 2024-11-28 at 11 14 46](https://github.com/user-attachments/assets/e4f7aca0-2e8d-4e6c-8166-c477cca273b3) | ![Simulator Screenshot - iPhone 16 Pro - 2024-11-28 at 10 41 59](https://github.com/user-attachments/assets/172ffadf-bbc6-40e6-bcd5-373a52de6004) |

2024-11-28 11:49 UTC, rnr approved these changes

2024-11-28 15:53 UTC, shafqat-muneer requested changes

2024-11-28 15:53 UTC, shafqat-muneer commented on Course/Course/Presentation/Subviews/CustomDisclosureGroup.swift
> +            if let _ = viewModel.sequentialsDownloadState[sequential.id] {
If we refactor it something like this:
```
    private func canDownloadAllSections(in chapter: CourseChapter) -> Bool {
        for sequential in chapter.childs where viewModel.sequentialsDownloadState[sequential.id] != nil {
            return true
        }
        return false
    }
```

Then we can avoid following two warnings:
```
Unused Optional Binding Violation: Prefer `!= nil` over `let _ =` (unused_optional_binding)

Prefer For-Where Violation: `where` clauses are preferred over a single `if` inside a `for` (for_where)
```

2024-11-29 05:06 UTC, shafqat-muneer approved these changes
LGTM 👍

2024-11-29 05:34 UTC, merged